"""add can_manage_guests and can_manage_spots to users

Revision ID: 788093be57f5
Revises: cc48f3ae5845
Create Date: 2026-07-02 15:45:34.330086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '788093be57f5'
down_revision: Union[str, Sequence[str], None] = 'cc48f3ae5845'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('can_manage_guests', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('users', sa.Column('can_manage_spots', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'can_manage_spots')
    op.drop_column('users', 'can_manage_guests')
    # ### end Alembic commands ###
