"""init

Revision ID: 917ac9762377
Revises: 
Create Date: 2026-06-24 10:35:18.158372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '917ac9762377'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('azure_oid', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('azure_oid'),
    sa.UniqueConstraint('email')
    )
    op.create_table('spots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('floor', sa.String(length=20), nullable=False),
    sa.Column('number', sa.String(length=20), nullable=False),
    sa.Column('spot_type', sa.Enum('ASSIGNED', 'SHARED', name='spottype'), nullable=False),
    sa.Column('assigned_user_id', sa.UUID(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('floor', 'number', name='uq_spots_floor_number')
    )
    op.create_table('releases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('spot_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('shift', sa.Enum('FULL_DAY', 'DAY', 'NIGHT', name='shift'), nullable=False),
    sa.Column('release_type', sa.Enum('POOL', 'TRANSFER', name='releasetype'), nullable=False),
    sa.Column('transfer_to_user_id', sa.UUID(), nullable=True),
    sa.Column('retracted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['spot_id'], ['spots.id'], ),
    sa.ForeignKeyConstraint(['transfer_to_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reservations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('spot_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('shift', sa.Enum('FULL_DAY', 'DAY', 'NIGHT', name='shift'), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['spot_id'], ['spots.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_reservations_active', 'reservations', ['spot_id', 'date', 'shift'], unique=True, postgresql_where='cancelled_at IS NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_reservations_active', table_name='reservations', postgresql_where='cancelled_at IS NULL')
    op.drop_table('reservations')
    op.drop_table('releases')
    op.drop_table('spots')
    op.drop_table('users')
    # ### end Alembic commands ###
