"""add guest_parkings

Revision ID: cc48f3ae5845
Revises: cedf875aec05
Create Date: 2026-07-02 12:51:47.082292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc48f3ae5845'
down_revision: Union[str, Sequence[str], None] = 'cedf875aec05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guest_parkings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('spot_id', sa.UUID(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time_from', sa.Time(), nullable=False),
    sa.Column('time_to', sa.Time(), nullable=False),
    sa.Column('guest_name', sa.String(length=255), nullable=False),
    sa.Column('guest_plate', sa.String(length=20), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('contact', sa.String(length=255), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['spot_id'], ['spots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guest_parkings')
    # ### end Alembic commands ###
