"""add can_view_reports to users

Revision ID: e7c666db6ae8
Revises: 788093be57f5
Create Date: 2026-07-02 16:18:07.294564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7c666db6ae8'
down_revision: Union[str, Sequence[str], None] = '788093be57f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('can_view_reports', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'can_view_reports')
    # ### end Alembic commands ###
